### ISSUE TITLE
snappy compatibility

### ISSUE THREAD

**Issue by zeflq** [jamesbrucepower/node-avro-io#11]
could you please fix the snappy version on package.json,there is some probleme with the latest vesion:
/var/www/producer/node_modules/node-avro-io/lib/datafile.js:270
        snappy.decompress(compressedData, snappy.parsers.raw, function(err
there is no variable parsers defined and the decompress methode is no longer an alias,so i change it with uncompress and it is ok

**Comment by jamesbrucepower** [comment]
Fixed
